name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true #For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1     
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore NuGet Packages
        run: nuget restore HelloWorldApp/HelloWorldApp.sln
      - name: Build and Publish App
        run: msbuild HelloWorldApp/HelloWorldApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: published_app
          path: HelloWorldApp\HelloWorldApp\bin\Release\
